name: Deploy

on: [push]

jobs:
  build:
    name: Run remote ssh command
    runs-on: ubuntu-latest
    env:
      GIT_SSH_COMMAND: ssh -i ${{ secrets.GH_KEY_LOCATION }}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GIT_SSH_COMMAND
          script: |
            cd ./hambot
            ./deploy.sh
